import { ApiError } from "./api-client";
import type { AllowedLink, MyProfile, PlatformId, UserProfileDetails } from "./types";

function record(value: unknown): Record<string, unknown> { if (typeof value !== "object" || value === null) throw new ApiError("마이페이지 응답 형식이 올바르지 않습니다.", 500, value); return value as Record<string, unknown>; }
function nullable(value: unknown) { return typeof value === "string" ? value : null; }
function details(value: unknown): UserProfileDetails | null { if (value === null || value === undefined) return null; const item = record(value); return { phoneNumber: nullable(item.phoneNumber), cashReceiptNumber: nullable(item.cashReceiptNumber), businessRegistrationNumber: nullable(item.businessRegistrationNumber), businessName: nullable(item.businessName), representativeName: nullable(item.representativeName), businessTypeItem: nullable(item.businessTypeItem), businessAddress: nullable(item.businessAddress), billingEmail: nullable(item.billingEmail), createdAt: typeof item.createdAt === "string" ? item.createdAt : "", updatedAt: typeof item.updatedAt === "string" ? item.updatedAt : "" }; }
export function parseMyProfile(value: unknown): MyProfile { const item = record(value); if (typeof item.id !== "string" || typeof item.loginId !== "string" || typeof item.usageExpiresAt !== "string" || !Array.isArray(item.allowedLinks)) throw new ApiError("마이페이지 응답 형식이 올바르지 않습니다.", 500, value); const platforms: PlatformId[] = ["panda", "soop", "youtube"]; const allowedLinks: AllowedLink[] = item.allowedLinks.map((link) => { const source = record(link); if (typeof source.id !== "string" || !platforms.includes(source.platform as PlatformId) || typeof source.url !== "string" || typeof source.createdAt !== "string") throw new ApiError("방송 링크 응답 형식이 올바르지 않습니다.", 500, value); return { id: source.id, platform: source.platform as PlatformId, url: source.url, createdAt: source.createdAt }; }); return { id: item.id, loginId: item.loginId, usageExpiresAt: item.usageExpiresAt, allowedLinks, profile: details(item.profile) }; }
export function formatPhone(value: string | null) { if (!value) return ""; const digits = value.replace(/\D/g, ""); return digits.length === 11 ? `${digits.slice(0,3)}-${digits.slice(3,7)}-${digits.slice(7)}` : value; }
export function formatBusinessNumber(value: string | null) { if (!value) return ""; const digits = value.replace(/\D/g, ""); return digits.length === 10 ? `${digits.slice(0,3)}-${digits.slice(3,5)}-${digits.slice(5)}` : value; }
export function maskPhone(value: string | null) { const digits = value?.replace(/\D/g, "") ?? ""; return digits.length >= 7 ? `${digits.slice(0,3)}****${digits.slice(-4)}` : "-"; }
export function maskBusinessNumber(value: string | null) { const digits = value?.replace(/\D/g, "") ?? ""; return digits.length === 10 ? `${digits.slice(0,3)}****${digits.slice(-3)}` : "-"; }
