"use client";

import { DragEvent, useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { apiClient, ApiError } from "@/lib/api-client";
import type { PlatformId } from "@/lib/types";
import { downloadPlatformAccountTemplate } from "@/lib/platform-account-template";
import { Modal } from "@/components/modal";
import { useToast } from "@/components/toast-provider";

type PlatformSummary = { platform: PlatformId; count: number };
type PlatformAccount = { id: string; platform: PlatformId; accountId: string; createdAt: string; updatedAt: string };
type ImportResult = { platform: PlatformId; totalRows: number; createdCount: number; skippedDuplicateCount: number };
const platformMeta: Record<PlatformId, { name: string; icon: string }> = { panda: { name: "팬더티비", icon: "P" }, soop: { name: "숲", icon: "S" }, youtube: { name: "유튜브", icon: "▶" } };
const platformIds: PlatformId[] = ["panda", "soop", "youtube"];
const MAX_FILE_SIZE = 5 * 1024 * 1024;

function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null; }
function isPlatform(value: unknown): value is PlatformId { return value === "panda" || value === "soop" || value === "youtube"; }
function parseSummaries(value: unknown): PlatformSummary[] { if (!Array.isArray(value)) throw new Error("플랫폼 계정 현황 응답이 올바르지 않습니다."); return value.map((item) => { if (!isRecord(item) || !isPlatform(item.platform) || typeof item.count !== "number") throw new Error("플랫폼 계정 현황 응답이 올바르지 않습니다."); return { platform: item.platform, count: item.count }; }); }
function parseAccounts(value: unknown): PlatformAccount[] { if (!Array.isArray(value)) throw new Error("플랫폼 계정 목록 응답이 올바르지 않습니다."); return value.map((item) => { if (!isRecord(item) || typeof item.id !== "string" || !isPlatform(item.platform) || typeof item.accountId !== "string" || typeof item.createdAt !== "string" || typeof item.updatedAt !== "string") throw new Error("플랫폼 계정 목록 응답이 올바르지 않습니다."); return { id: item.id, platform: item.platform, accountId: item.accountId, createdAt: item.createdAt, updatedAt: item.updatedAt }; }); }
function parseImportResult(value: unknown): ImportResult { if (!isRecord(value) || !isPlatform(value.platform) || typeof value.totalRows !== "number" || typeof value.createdCount !== "number" || typeof value.skippedDuplicateCount !== "number") throw new Error("업로드 결과 응답이 올바르지 않습니다."); return { platform: value.platform, totalRows: value.totalRows, createdCount: value.createdCount, skippedDuplicateCount: value.skippedDuplicateCount }; }
function date(value: string) { return new Intl.DateTimeFormat("ko-KR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }

export default function PlatformAccountsPage() {
  const router = useRouter(); const { showToast } = useToast(); const fileInput = useRef<HTMLInputElement>(null);
  const [selected, setSelected] = useState<PlatformId>("panda"); const [summaries, setSummaries] = useState<PlatformSummary[]>([]); const [accounts, setAccounts] = useState<PlatformAccount[]>([]); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [dragging, setDragging] = useState(false); const [deleting, setDeleting] = useState<Set<string>>(new Set()); const [error, setError] = useState(""); const [uploadError, setUploadError] = useState(""); const [result, setResult] = useState<ImportResult | null>(null); const [deleteTarget, setDeleteTarget] = useState<PlatformAccount | null>(null);
  const handleError = useCallback((requestError: unknown, fallback: string) => { if (requestError instanceof ApiError && requestError.status === 403) { showToast("관리자 권한이 없습니다.", "error"); router.replace("/monitor"); return "관리자 권한이 없습니다."; } return requestError instanceof Error ? requestError.message : fallback; }, [router, showToast]);
  const loadSummaries = useCallback(async () => setSummaries(parseSummaries(await apiClient<unknown>("/api/admin/platform-accounts"))), []);
  const loadAccounts = useCallback(async (platform: PlatformId) => setAccounts(parseAccounts(await apiClient<unknown>(`/api/admin/platform-accounts/${platform}`))), []);
  const reload = useCallback(async (platform: PlatformId) => { await Promise.all([loadSummaries(), loadAccounts(platform)]); }, [loadAccounts, loadSummaries]);
  useEffect(() => { let active = true; Promise.all([apiClient<unknown>("/api/admin/platform-accounts"), apiClient<unknown>(`/api/admin/platform-accounts/${selected}`)]).then(([summaryData, accountData]) => { if (active) { setSummaries(parseSummaries(summaryData)); setAccounts(parseAccounts(accountData)); setError(""); } }).catch((requestError) => { if (active) setError(handleError(requestError, "플랫폼 계정을 불러오지 못했습니다.")); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [handleError, selected]);
  function selectPlatform(platform: PlatformId) { if (platform === selected) return; setLoading(true); setSelected(platform); setError(""); }
  async function upload(file?: File) { if (!file || uploading) return; setUploadError(""); if (!file.name.toLowerCase().endsWith(".xlsx")) { setUploadError(".xlsx 파일만 업로드할 수 있습니다."); return; } if (file.size > MAX_FILE_SIZE) { setUploadError("5MB 이하의 엑셀 파일을 선택해주세요."); return; } setUploading(true); const body = new FormData(); body.append("file", file); try { const imported = parseImportResult(await apiClient<unknown>(`/api/admin/platform-accounts/${selected}/import`, { method: "POST", body })); await reload(selected); setResult(imported); } catch (requestError) { const status = requestError instanceof ApiError ? requestError.status : 0; setUploadError(status === 413 ? "5MB 이하의 엑셀 파일을 선택해주세요." : handleError(requestError, "엑셀 파일을 업로드하지 못했습니다.")); } finally { setUploading(false); if (fileInput.current) fileInput.current.value = ""; } }
  function drop(event: DragEvent<HTMLLabelElement>) { event.preventDefault(); setDragging(false); void upload(event.dataTransfer.files[0]); }
  async function removeAccount(account: PlatformAccount) { if (deleting.has(account.id)) return; setDeleting((current) => new Set(current).add(account.id)); try { await apiClient(`/api/admin/platform-accounts/${account.platform}/${account.id}`, { method: "DELETE" }); setDeleteTarget(null); await reload(selected); showToast("플랫폼 계정을 삭제했습니다.", "success"); } catch (requestError) { const message = requestError instanceof ApiError && requestError.status === 404 ? "이미 삭제되었거나 존재하지 않는 계정입니다." : handleError(requestError, "플랫폼 계정을 삭제하지 못했습니다."); showToast(message, "error"); } finally { setDeleting((current) => { const next = new Set(current); next.delete(account.id); return next; }); } }
  return <><header className="admin-page-head"><div><span className="eyebrow">PLATFORM ACCOUNTS</span><h1>플랫폼 계정 관리</h1><p className="muted">방송 자동 시청에 사용할 플랫폼 계정을 엑셀로 등록하고 관리합니다.</p></div><button className="secondary" type="button" onClick={downloadPlatformAccountTemplate}>엑셀 양식 다운로드</button></header>
    <div className="platform-account-tabs">{platformIds.map((platform) => <button type="button" className={`platform-account-tab ${platform} ${selected === platform ? "active" : ""}`} onClick={() => selectPlatform(platform)} key={platform}><span className="platform-account-icon">{platformMeta[platform].icon}</span><span><strong>{platformMeta[platform].name}</strong><small>{platform}</small></span><b>{summaries.find((item) => item.platform === platform)?.count ?? 0}개</b></button>)}</div>
    <section className="platform-upload-card"><div><h2>{platformMeta[selected].name} 계정 업로드</h2><p>첫 시트의 A1은 <code>id</code>, B1은 <code>password</code>로 작성하고 데이터는 2행부터 입력해주세요.</p></div><label className={`platform-upload-zone ${dragging ? "dragging" : ""}`} onDragEnter={(event) => { event.preventDefault(); setDragging(true); }} onDragOver={(event) => event.preventDefault()} onDragLeave={() => setDragging(false)} onDrop={drop}><span>↑</span><strong>{uploading ? "업로드 중..." : "엑셀 파일을 놓거나 클릭하세요"}</strong><small>.xlsx · 최대 5MB · 최대 1,000개</small><input ref={fileInput} type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" disabled={uploading} onChange={(event) => void upload(event.target.files?.[0])} /></label><div className="platform-upload-help">ID와 비밀번호의 앞자리 0이 유지되도록 두 열을 반드시 <strong>텍스트 형식</strong>으로 작성해주세요.</div>{uploadError && <div className="alert error">{uploadError}</div>}</section>
    <section className="management-card platform-account-list"><div className="toolbar"><div><strong>{platformMeta[selected].name} 계정</strong><span className="muted">총 {accounts.length}개</span></div><button className="secondary compact" type="button" disabled={loading} onClick={() => { setLoading(true); void reload(selected).catch((requestError) => setError(handleError(requestError, "새로고침하지 못했습니다."))).finally(() => setLoading(false)); }}>새로고침</button></div>{error && <div className="alert error">{error}</div>}{loading ? <div className="table-empty">플랫폼 계정을 불러오는 중입니다.</div> : accounts.length ? <><div className="table-scroll"><table className="platform-account-table"><thead><tr><th>순번</th><th>계정 아이디</th><th>플랫폼</th><th>등록일</th><th>관리</th></tr></thead><tbody>{accounts.map((account, index) => <tr key={account.id}><td>{index + 1}</td><td><strong>{account.accountId}</strong></td><td><span className={`platform-chip ${account.platform}`}>{platformMeta[account.platform].name}</span></td><td>{date(account.createdAt)}</td><td><button className="danger compact" type="button" disabled={deleting.has(account.id)} onClick={() => setDeleteTarget(account)}>{deleting.has(account.id) ? "삭제 중..." : "삭제"}</button></td></tr>)}</tbody></table></div><div className="platform-account-mobile">{accounts.map((account, index) => <article key={account.id}><span>{index + 1}</span><div><strong>{account.accountId}</strong><small>{platformMeta[account.platform].name} · {date(account.createdAt)}</small></div><button className="danger compact" type="button" disabled={deleting.has(account.id)} onClick={() => setDeleteTarget(account)}>삭제</button></article>)}</div></> : <div className="table-empty">등록된 플랫폼 계정이 없습니다.</div>}</section>
    {result && <Modal title="엑셀 업로드 완료" onClose={() => setResult(null)}><div className="import-result"><span className={`platform-account-icon ${result.platform}`}>{platformMeta[result.platform].icon}</span><p>총 <strong>{result.totalRows}개</strong> 중 <strong>{result.createdCount}개</strong>를 등록했습니다.<br />중복 계정 {result.skippedDuplicateCount}개는 건너뛰었습니다.</p><button className="primary full" type="button" onClick={() => setResult(null)}>확인</button></div></Modal>}
    {deleteTarget && <Modal title="플랫폼 계정 삭제" onClose={() => { if (!deleting.has(deleteTarget.id)) setDeleteTarget(null); }} closeDisabled={deleting.has(deleteTarget.id)}><div className="delete-account-dialog"><p><strong>{deleteTarget.accountId}</strong> 계정을 삭제하시겠습니까?<br />삭제한 계정 정보는 복구할 수 없습니다.</p><div className="modal-actions"><button className="secondary" type="button" disabled={deleting.has(deleteTarget.id)} onClick={() => setDeleteTarget(null)}>취소</button><button className="danger" type="button" disabled={deleting.has(deleteTarget.id)} onClick={() => void removeAccount(deleteTarget)}>{deleting.has(deleteTarget.id) ? "삭제 중..." : "삭제"}</button></div></div></Modal>}
  </>;
}
