"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { apiClient, ApiError } from "@/lib/api-client";
import { formatDate, isExpired, remainingDays } from "@/lib/admin-api";
import { formatBusinessNumber, formatPhone, parseMyProfile } from "@/lib/profile-api";
import type { MyProfile, UserProfileDetails } from "@/lib/types";
import { ProtectedRoute } from "@/components/protected-route";
import { useAuth } from "@/components/auth-provider";
import { useToast } from "@/components/toast-provider";
import { PasswordChangeCard } from "@/components/password-change-card";
import { PlatformLinkFields } from "@/components/platform-link-fields";
import { emptyPlatformLinks, linksToValues, validatePlatformLinks, valuesToRequest, type PlatformLinkErrors, type PlatformLinkValues } from "@/lib/platform-links";
import type { PlatformId } from "@/lib/types";

type EditableProfile = { [K in keyof Pick<UserProfileDetails, "phoneNumber" | "cashReceiptNumber" | "businessRegistrationNumber" | "businessName" | "representativeName" | "businessTypeItem" | "businessAddress" | "billingEmail">]: string };
const emptyProfile: EditableProfile = { phoneNumber: "", cashReceiptNumber: "", businessRegistrationNumber: "", businessName: "", representativeName: "", businessTypeItem: "", businessAddress: "", billingEmail: "" };

export default function MyPage() {
  const { user, setAuthenticatedUser } = useAuth(); const { showToast } = useToast(); const router = useRouter();
  const [data, setData] = useState<MyProfile | null>(null); const [form, setForm] = useState<EditableProfile>(emptyProfile); const [initialForm, setInitialForm] = useState<EditableProfile>(emptyProfile); const [links, setLinks] = useState<PlatformLinkValues>(emptyPlatformLinks); const [linkErrors, setLinkErrors] = useState<PlatformLinkErrors>({}); const [loading, setLoading] = useState(true); const [savingProfile, setSavingProfile] = useState(false); const [savingLinks, setSavingLinks] = useState(false); const [error, setError] = useState("");
  const applyProfile = useCallback((profile: MyProfile) => { setData(profile); const values: EditableProfile = { phoneNumber: formatPhone(profile.profile?.phoneNumber ?? null), cashReceiptNumber: formatPhone(profile.profile?.cashReceiptNumber ?? null), businessRegistrationNumber: formatBusinessNumber(profile.profile?.businessRegistrationNumber ?? null), businessName: profile.profile?.businessName ?? "", representativeName: profile.profile?.representativeName ?? "", businessTypeItem: profile.profile?.businessTypeItem ?? "", businessAddress: profile.profile?.businessAddress ?? "", billingEmail: profile.profile?.billingEmail ?? "" }; setForm(values); setInitialForm(values); setLinks(linksToValues(profile.allowedLinks)); setLinkErrors({}); }, []);
  useEffect(() => { let active = true; apiClient<unknown>("/api/users/me/profile").then((response) => { if (active) applyProfile(parseMyProfile(response)); }).catch((requestError) => { if (active) setError(requestError instanceof Error ? requestError.message : "마이페이지를 불러오지 못했습니다."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [applyProfile]);
  useEffect(() => { if (!loading && user?.role === "admin") router.replace("/admin/users"); }, [loading, router, user]);
  function update<K extends keyof EditableProfile>(key: K, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  async function saveProfile(event: FormEvent) { event.preventDefault(); if (savingProfile || !data) return; setError(""); if (form.phoneNumber && !/^[0-9+()\s-]{8,20}$/.test(form.phoneNumber)) return setError("휴대폰번호 형식을 확인해주세요."); if (form.cashReceiptNumber && !/^[0-9-]{10,20}$/.test(form.cashReceiptNumber)) return setError("현금영수증번호 형식을 확인해주세요."); if (form.businessRegistrationNumber && !/^\d{3}-?\d{2}-?\d{5}$/.test(form.businessRegistrationNumber)) return setError("사업자등록번호 10자리를 확인해주세요."); if (form.billingEmail && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.billingEmail)) return setError("수신메일 형식을 확인해주세요."); const body = Object.fromEntries(Object.entries(form).filter(([key, value]) => value !== initialForm[key as keyof EditableProfile]).map(([key, value]) => [key, value.trim() || null])); if (!Object.keys(body).length) return showToast("변경된 정보가 없습니다."); setSavingProfile(true); try { const updated = parseMyProfile(await apiClient<unknown>("/api/users/me/profile", { method: "PATCH", body: JSON.stringify(body) })); applyProfile(updated); showToast("마이페이지 정보가 저장되었습니다.", "success"); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "정보를 저장하지 못했습니다."); } finally { setSavingProfile(false); } }
  function updateLink(platform: PlatformId, value: string) { setLinks((current) => ({ ...current, [platform]: value })); setLinkErrors((current) => ({ ...current, [platform]: undefined })); }
  async function saveLinks() { if (savingLinks || !data) return; const validation = validatePlatformLinks(links); setLinkErrors(validation); if (Object.keys(validation).length) return; setSavingLinks(true); setError(""); try { const updated = parseMyProfile(await apiClient<unknown>("/api/users/me/links", { method: "PUT", body: JSON.stringify({ allowedLinks: valuesToRequest(links) }) })); applyProfile(updated); if (user) setAuthenticatedUser({ ...user, usageExpiresAt: updated.usageExpiresAt, allowedLinks: updated.allowedLinks }); showToast("방송 링크가 저장되었습니다.", "success"); } catch (requestError) { setError(requestError instanceof ApiError && requestError.status === 400 ? "링크 형식 또는 플랫폼 중복 여부를 확인해주세요." : requestError instanceof Error ? requestError.message : "방송 링크를 저장하지 못했습니다."); } finally { setSavingLinks(false); } }
  if (loading || user?.role !== "user") return <ProtectedRoute><main className="loading-screen">마이페이지를 불러오고 있습니다.</main></ProtectedRoute>;
  if (!data) return <ProtectedRoute><main className="account-page"><div className="alert error">{error || "마이페이지를 불러오지 못했습니다."}</div></main></ProtectedRoute>;
  const expired = isExpired(data.usageExpiresAt);
  return <ProtectedRoute><main className="mypage"><header className="account-page-head"><div><span className="eyebrow">MY PAGE</span><h1>마이페이지</h1><p className="muted">이용정보와 결제 증빙 정보를 관리합니다.</p></div><button className="secondary" onClick={() => router.push("/monitor")}>시청자 프로그램</button></header>
    {expired && <div className="onboarding-notice"><strong>이용기간이 만료되었습니다.</strong><span>시청자 프로그램을 이용하려면 이용권 결제가 필요합니다.</span></div>}
    {error && <div className="alert error">{error}</div>}
    <div className="mypage-grid"><section className="mypage-section mypage-account-card"><div className="mypage-title"><span>01</span><div><h2>계정 및 이용정보</h2><p>시청자 프로그램 이용기간을 확인할 수 있습니다.</p></div></div><div className="account-status-grid"><div><span>아이디</span><strong>{data.loginId}</strong></div><div><span>이용기간</span><strong>{expired ? <i className="expiry-badge">이용기간 만료</i> : <i className="status-pill active">이용 중</i>}</strong></div><div><span>이용 종료일</span><strong>{expired ? "이용기간이 만료되었습니다." : `${formatDate(data.usageExpiresAt)}까지 이용 가능`}</strong></div><div><span>남은 이용일</span><strong>{expired ? "만료됨" : `${remainingDays(data.usageExpiresAt)}일 남음`}</strong></div></div></section>
    <section className="mypage-section mypage-links-card"><div className="mypage-title"><span>03</span><div><h2>내 방송 링크</h2><p>현재 팬더티비 방송 링크를 등록할 수 있습니다.</p></div></div><div className="mypage-links"><PlatformLinkFields values={links} errors={linkErrors} onChange={updateLink} disabledPlatforms={["soop", "youtube"]} /><div className="mypage-actions"><button className="primary" type="button" disabled={savingLinks} onClick={() => void saveLinks()}>{savingLinks ? "저장 중..." : "링크 저장"}</button></div></div></section>
    <form onSubmit={saveProfile}><section className="mypage-section mypage-cash-card"><div className="mypage-title"><span>02</span><div><h2>현금영수증 정보</h2><p>필요한 항목만 선택적으로 입력할 수 있습니다.</p></div></div><div className="form-grid"><label>휴대폰번호<input type="text" value={form.phoneNumber ?? ""} onChange={(event) => update("phoneNumber", event.target.value)} placeholder="010-1234-5678" /></label><label>현금영수증번호<input type="text" value={form.cashReceiptNumber ?? ""} onChange={(event) => update("cashReceiptNumber", event.target.value)} placeholder="010-1234-5678" /></label></div></section>
      <section className="mypage-section mypage-tax-card"><div className="mypage-title"><span>04</span><div><h2>세금계산서 정보</h2><p>세금계산서 발행에 필요한 정보를 입력하세요.</p></div></div><div className="form-grid"><label>사업자등록번호<input type="text" value={form.businessRegistrationNumber ?? ""} onChange={(event) => update("businessRegistrationNumber", event.target.value)} placeholder="123-45-67890" /></label><label>상호명<input type="text" value={form.businessName ?? ""} onChange={(event) => update("businessName", event.target.value)} /></label><label>대표자명<input type="text" value={form.representativeName ?? ""} onChange={(event) => update("representativeName", event.target.value)} /></label><label>업태/종목<input type="text" value={form.businessTypeItem ?? ""} onChange={(event) => update("businessTypeItem", event.target.value)} /></label><label className="full-field">사업장주소<textarea maxLength={1000} value={form.businessAddress ?? ""} onChange={(event) => update("businessAddress", event.target.value)} /></label><label className="full-field">수신메일<input type="email" value={form.billingEmail ?? ""} onChange={(event) => update("billingEmail", event.target.value)} placeholder="billing@example.com" /></label></div><div className="mypage-actions"><button className="primary" disabled={savingProfile} type="submit">{savingProfile ? "저장 중..." : "정보 저장"}</button></div></section></form><PasswordChangeCard /></div>
  </main></ProtectedRoute>;
}
